// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/req_http_message.proto

package com.insping.libra.proto;

public final class ReqHttpMessage {
  private ReqHttpMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqHttpMessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReqHttpMessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string httpReqMessage = 1;</code>
     */
    java.lang.String getHttpReqMessage();
    /**
     * <code>string httpReqMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getHttpReqMessageBytes();
  }
  /**
   * <pre>
   * Http消息包
   * </pre>
   *
   * Protobuf type {@code proto.ReqHttpMessageData}
   */
  public  static final class ReqHttpMessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReqHttpMessageData)
      ReqHttpMessageDataOrBuilder {
    // Use ReqHttpMessageData.newBuilder() to construct.
    private ReqHttpMessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqHttpMessageData() {
      httpReqMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReqHttpMessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              httpReqMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.insping.libra.proto.ReqHttpMessage.internal_static_proto_ReqHttpMessageData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.insping.libra.proto.ReqHttpMessage.internal_static_proto_ReqHttpMessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.class, com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.Builder.class);
    }

    public static final int HTTPREQMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object httpReqMessage_;
    /**
     * <code>string httpReqMessage = 1;</code>
     */
    public java.lang.String getHttpReqMessage() {
      java.lang.Object ref = httpReqMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpReqMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string httpReqMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHttpReqMessageBytes() {
      java.lang.Object ref = httpReqMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpReqMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHttpReqMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, httpReqMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHttpReqMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, httpReqMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData)) {
        return super.equals(obj);
      }
      com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData other = (com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData) obj;

      boolean result = true;
      result = result && getHttpReqMessage()
          .equals(other.getHttpReqMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HTTPREQMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getHttpReqMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Http消息包
     * </pre>
     *
     * Protobuf type {@code proto.ReqHttpMessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReqHttpMessageData)
        com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.insping.libra.proto.ReqHttpMessage.internal_static_proto_ReqHttpMessageData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.insping.libra.proto.ReqHttpMessage.internal_static_proto_ReqHttpMessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.class, com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.Builder.class);
      }

      // Construct using com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        httpReqMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.insping.libra.proto.ReqHttpMessage.internal_static_proto_ReqHttpMessageData_descriptor;
      }

      public com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData getDefaultInstanceForType() {
        return com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.getDefaultInstance();
      }

      public com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData build() {
        com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData buildPartial() {
        com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData result = new com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData(this);
        result.httpReqMessage_ = httpReqMessage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData) {
          return mergeFrom((com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData other) {
        if (other == com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData.getDefaultInstance()) return this;
        if (!other.getHttpReqMessage().isEmpty()) {
          httpReqMessage_ = other.httpReqMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object httpReqMessage_ = "";
      /**
       * <code>string httpReqMessage = 1;</code>
       */
      public java.lang.String getHttpReqMessage() {
        java.lang.Object ref = httpReqMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          httpReqMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string httpReqMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHttpReqMessageBytes() {
        java.lang.Object ref = httpReqMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpReqMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string httpReqMessage = 1;</code>
       */
      public Builder setHttpReqMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        httpReqMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string httpReqMessage = 1;</code>
       */
      public Builder clearHttpReqMessage() {
        
        httpReqMessage_ = getDefaultInstance().getHttpReqMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string httpReqMessage = 1;</code>
       */
      public Builder setHttpReqMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        httpReqMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ReqHttpMessageData)
    }

    // @@protoc_insertion_point(class_scope:proto.ReqHttpMessageData)
    private static final com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData();
    }

    public static com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqHttpMessageData>
        PARSER = new com.google.protobuf.AbstractParser<ReqHttpMessageData>() {
      public ReqHttpMessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqHttpMessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqHttpMessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHttpMessageData> getParserForType() {
      return PARSER;
    }

    public com.insping.libra.proto.ReqHttpMessage.ReqHttpMessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReqHttpMessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReqHttpMessageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protos/req_http_message.proto\022\005proto\"," +
      "\n\022ReqHttpMessageData\022\026\n\016httpReqMessage\030\001" +
      " \001(\tB=\n\027com.insping.libra.protoB\016ReqHttp" +
      "Message\252\002\021LibraClient.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ReqHttpMessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ReqHttpMessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReqHttpMessageData_descriptor,
        new java.lang.String[] { "HttpReqMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
